config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resource :session, only: [:create, :destroy, :new] 
  resources :subs do 
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:index] do 
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create] do
    resources :comments, only: [:new]
  end
  resources :comments, only:[:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user

  belongs_to :post

  has_many :comments,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  belongs_to :comment,
    optional: true,
    foreign_key: :parent_comment_id,
    class_name: :Comment



end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :user_id, presence: true

  has_many :postsubs
  
  has_many :subs,
    through: :postsubs,
    source: :sub
  
  belongs_to :user

  has_many :comments
  


end

app/models/postsub.rb
class Postsub < ApplicationRecord
  belongs_to :post 
  belongs_to :sub

end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, :user_id, presence: true
  
  belongs_to :user
  has_many :postsubs
  has_many :posts,
  through: :postsubs,
  source: :post
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6}, allow_nil: true
  attr_reader :password
  after_initialize :ensure_session_token

  has_many :subs

  has_many :posts

  has_many :comments

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def reset_session_token
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def login(user)
    session[:session_token] = user.reset_session_token
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
    @current_user = nil
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def new
    @comment = Comment.new
    if params[:post_id]
      @comment.post_id = params[:post_id]
    elsif params[:comment_id]

      @comment.parent_comment_id = params[:comment_id]
      @comment.post_id = @comment.comment.post_id
    end
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :require_logged_in
before_action :authors_only, only: [:edit, :update]


  def authors_only
    if current_user.posts.find(params[:id]).nil?
      redirect_to post_url(params[:id])
    end 
  end

  def new
    @post = Post.new
    @post.sub_id = params[:sub_id]
  end

  def create
    @post = Post.new(post_params)

    @post.user_id = current_user.id

    if @post.save
      redirect_to post_url(@post)
    else 
      flash.now[:errors] = @post.errors.full_messages
      render :new

    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to post_url(@post)
    else 
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private 

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by_credentials(params[:user][:username],params[:user][:password])

    if user
      login(user)
      redirect_to subs_url
    else 
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in
  before_action :moderators_only, only:[:edit, :update]

  def moderators_only
    if current_user.subs.find(params[:id]).nil?
      redirect_to sub_url(params[:id])
    end 
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = current_user.subs.find(params[:id])

    if @sub.update(sub_params)
      redirect_to sub_link(@sub)
    else 
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end
  
  private
  
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new   
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to subs_url
    else 
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to subs_url
    else 
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])

    @user.destroy

    redirect_to new_user_url
  end 

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<li>

<a href="<%=comment_url(comment)%>"> <%= comment.content%></a>

</li>
<ul>

<%comment.comments.each do |sub_comment| %>
<%=render("comments/form", comment: sub_comment) %>
<% end %>
</ul>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<form action="<%=comments_url%>" method="post">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
<% if params[:comment_id] %>
<input type="hidden" name="comment[parent_comment_id]" value="<%=@comment.parent_comment_id%>">
<% end %>

<input type="hidden" name="comment[post_id]" value="<%=@comment.post_id%>">

<label for="content">Comment
<textarea name="comment[content]" ></textarea>
</label>

<input type="submit" value="Add Comment">

</form>

app/views/comments/show.html.erb
<h1><%= @comment.content %></h1>


<a href="<%=new_comment_comment_url(@comment)%>">Add comment</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <% if current_user %>
     <h2><%= current_user.username %></h2>
     <form action="<%=session_url%>" method="post">
     <input type="hidden" name="_method" value="delete">
     <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
     <input type="submit" value="Log Out">
     </form>

     <% else %>
      <a href="<%=new_session_url%>">Sign In</a>
      <a href="<%=new_user_url%>">Sign Up</a>

  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Update Post</h1>


<form action="<%=post_url(@post)%>" method="post">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
<input type="hidden" name="_method" value="patch">
<label for="title">Title
<input type="text" name="post[title]" value="<%=@post.title%>">
</label>
<br>
<label for="URL">URL
<input type="text" name="post[url]" value="<%=@post.url%>" >
</label>
<br>
<label for="content">Post
<textarea name="post[content]" ><%=@post.content%></textarea>
</label>
<br>

<% Sub.all.each do |sub| %>
  <label for=""> <%= sub.title %>
  <input type="checkbox" 
  name="post[sub_ids][]" 
  value="<%=sub.id%>"
  <%= "checked" if @post.sub_ids.include?(sub.id)%>
  >
  </label>
<br>
<% end %>

<input type="submit" value="Edit Post">

</form>

app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%=posts_url%>" method="post">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

<label for="title">Title
<input type="text" name="post[title]" >
</label>
<br>
<label for="URL">URL
<input type="text" name="post[url]" >
</label>
<br>
<label for="content">Post
<textarea name="post[content]"></textarea>
</label>
<br>

<% Sub.all.each do |sub| %>
  <label for=""> <%= sub.title %>
  <input type="checkbox" name="post[sub_ids][]" value="<%=sub.id%>">
  </label>
<br>
<% end %>

<input type="submit" value="Create Post">
</form>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p> <%= @post.content %> </p>

<a href="<%=subs_url%>">Back to Subs</a>

<a href="<%=edit_post_url(@post.id)%>">Edit Post</a>

<a href="<%=new_post_comment_url(@post.id)%>">Add Comment</a>
<ul>
<% @post.comments.where(parent_comment_id: nil).includes(:comments).each do |comment| %>

<%=render("comments/form", comment: comment) %>

<% end %>

</ul>

app/views/subs/index.html.erb
<h1>Subs</h1>

<a href="<%=new_sub_url%>">Create a new Sub</a>

<ul>
<% Sub.all.each do |sub| %>
  <li>
  <span>
    <a href="<%=sub_url(sub)%>"><%=sub.title%></a>
    <form action="<%=sub_url(sub)%>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
     <input type="submit" value="Delete Sub">
     </form>
     </span>
  </li>
<% end %>
</ul>

app/views/subs/new.html.erb
<h1>New Sub</h1>

<form action="<%=subs_url%>" method="post">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

<label for="title">Title
<input type="text" name="sub[title]">
</label>

<label for="description">Description
<textarea name="sub[description]" ></textarea>
</label>

<input type="submit" value="Create New Sub">
</form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<a href="<%=subs_url%>">Subs</a>

<a href="<%=new_sub_post_url(@sub)%>">New Post</a>


<ul>
<% @sub.posts.each do |post|%>

<li>
<a href="<%=post_url(post)%>"><%= post.title %></a>
  <br>
  <%= post.content %>
</li>
<% end%>
</ul>

app/views/users/new.html.erb
<h1>Create Account</h1>

<form action="<%=users_url%>" method="post">

<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

<label for="username">Username
<input type="text" name="user[username]">
</label>
<br>
<label for="password">Password
<input type="password" name="user[password]">
</label>
<br>
<input type="submit" value="Create Account">
</form>